language: csharp
solution: CardboardFactorySolution.sln
install:
  - nuget restore solution-name.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release solution-name.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./CardboardFactory.Core.Test/bin/Release/CardboardFactory.Core.Test.dll
