//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardboardFactory.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CardboardFactory.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Д.
        /// </summary>
        public static string CardboardBrands_D {
            get {
                return ResourceManager.GetString("CardboardBrands_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to П.
        /// </summary>
        public static string CardboardBrands_P {
            get {
                return ResourceManager.GetString("CardboardBrands_P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Т.
        /// </summary>
        public static string CardboardBrands_T {
            get {
                return ResourceManager.GetString("CardboardBrands_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21.
        /// </summary>
        public static string CardboardClasses_Class21 {
            get {
                return ResourceManager.GetString("CardboardClasses_Class21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22.
        /// </summary>
        public static string CardboardClasses_Class22 {
            get {
                return ResourceManager.GetString("CardboardClasses_Class22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 23.
        /// </summary>
        public static string CardboardClasses_Class23 {
            get {
                return ResourceManager.GetString("CardboardClasses_Class23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бурый.
        /// </summary>
        public static string CardboardColors_Brown {
            get {
                return ResourceManager.GetString("CardboardColors_Brown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Белый.
        /// </summary>
        public static string CardboardColors_White {
            get {
                return ResourceManager.GetString("CardboardColors_White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бело/белый.
        /// </summary>
        public static string CardboardColors_WhiteWhite {
            get {
                return ResourceManager.GetString("CardboardColors_WhiteWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string CorrugationTypes_All {
            get {
                return ResourceManager.GetString("CorrugationTypes_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;C&quot; волна.
        /// </summary>
        public static string CorrugationTypes_C {
            get {
                return ResourceManager.GetString("CorrugationTypes_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;E&quot; волна.
        /// </summary>
        public static string CorrugationTypes_E {
            get {
                return ResourceManager.GetString("CorrugationTypes_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;C + E&quot; волна.
        /// </summary>
        public static string CorrugationTypes_EAndC {
            get {
                return ResourceManager.GetString("CorrugationTypes_EAndC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полиграф. картон.
        /// </summary>
        public static string CorrugationTypes_Polygraphy {
            get {
                return ResourceManager.GetString("CorrugationTypes_Polygraphy", resourceCulture);
            }
        }
    }
}
